# coding: utf-8

# flake8: noqa

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.addresses_api import AddressesApi
from swagger_client.api.customer_addresses_api import CustomerAddressesApi
from swagger_client.api.customers_api import CustomersApi
from swagger_client.api.error_logs_api import ErrorLogsApi
from swagger_client.api.product_categories_api import ProductCategoriesApi
from swagger_client.api.product_descriptions_api import ProductDescriptionsApi
from swagger_client.api.product_model_product_descriptions_api import ProductModelProductDescriptionsApi
from swagger_client.api.product_models_api import ProductModelsApi
from swagger_client.api.products_api import ProductsApi
from swagger_client.api.sales_order_details_api import SalesOrderDetailsApi
from swagger_client.api.sales_order_headers_api import SalesOrderHeadersApi
from swagger_client.api.values_api import ValuesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.address import Address
from swagger_client.models.customer import Customer
from swagger_client.models.customer_address import CustomerAddress
from swagger_client.models.error_log import ErrorLog
from swagger_client.models.product import Product
from swagger_client.models.product_category import ProductCategory
from swagger_client.models.product_description import ProductDescription
from swagger_client.models.product_model import ProductModel
from swagger_client.models.product_model_product_description import ProductModelProductDescription
from swagger_client.models.sales_order_detail import SalesOrderDetail
from swagger_client.models.sales_order_header import SalesOrderHeader
