# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.product import Product  # noqa: F401,E501
from swagger_client.models.product_model_product_description import ProductModelProductDescription  # noqa: F401,E501


class ProductModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_model_id': 'int',
        'name': 'str',
        'catalog_description': 'str',
        'rowguid': 'str',
        'modified_date': 'datetime',
        'product': 'list[Product]',
        'product_model_product_description': 'list[ProductModelProductDescription]'
    }

    attribute_map = {
        'product_model_id': 'productModelId',
        'name': 'name',
        'catalog_description': 'catalogDescription',
        'rowguid': 'rowguid',
        'modified_date': 'modifiedDate',
        'product': 'product',
        'product_model_product_description': 'productModelProductDescription'
    }

    def __init__(self, product_model_id=None, name=None, catalog_description=None, rowguid=None, modified_date=None, product=None, product_model_product_description=None):  # noqa: E501
        """ProductModel - a model defined in Swagger"""  # noqa: E501

        self._product_model_id = None
        self._name = None
        self._catalog_description = None
        self._rowguid = None
        self._modified_date = None
        self._product = None
        self._product_model_product_description = None
        self.discriminator = None

        if product_model_id is not None:
            self.product_model_id = product_model_id
        if name is not None:
            self.name = name
        if catalog_description is not None:
            self.catalog_description = catalog_description
        if rowguid is not None:
            self.rowguid = rowguid
        if modified_date is not None:
            self.modified_date = modified_date
        if product is not None:
            self.product = product
        if product_model_product_description is not None:
            self.product_model_product_description = product_model_product_description

    @property
    def product_model_id(self):
        """Gets the product_model_id of this ProductModel.  # noqa: E501


        :return: The product_model_id of this ProductModel.  # noqa: E501
        :rtype: int
        """
        return self._product_model_id

    @product_model_id.setter
    def product_model_id(self, product_model_id):
        """Sets the product_model_id of this ProductModel.


        :param product_model_id: The product_model_id of this ProductModel.  # noqa: E501
        :type: int
        """

        self._product_model_id = product_model_id

    @property
    def name(self):
        """Gets the name of this ProductModel.  # noqa: E501


        :return: The name of this ProductModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProductModel.


        :param name: The name of this ProductModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def catalog_description(self):
        """Gets the catalog_description of this ProductModel.  # noqa: E501


        :return: The catalog_description of this ProductModel.  # noqa: E501
        :rtype: str
        """
        return self._catalog_description

    @catalog_description.setter
    def catalog_description(self, catalog_description):
        """Sets the catalog_description of this ProductModel.


        :param catalog_description: The catalog_description of this ProductModel.  # noqa: E501
        :type: str
        """

        self._catalog_description = catalog_description

    @property
    def rowguid(self):
        """Gets the rowguid of this ProductModel.  # noqa: E501


        :return: The rowguid of this ProductModel.  # noqa: E501
        :rtype: str
        """
        return self._rowguid

    @rowguid.setter
    def rowguid(self, rowguid):
        """Sets the rowguid of this ProductModel.


        :param rowguid: The rowguid of this ProductModel.  # noqa: E501
        :type: str
        """

        self._rowguid = rowguid

    @property
    def modified_date(self):
        """Gets the modified_date of this ProductModel.  # noqa: E501


        :return: The modified_date of this ProductModel.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_date

    @modified_date.setter
    def modified_date(self, modified_date):
        """Sets the modified_date of this ProductModel.


        :param modified_date: The modified_date of this ProductModel.  # noqa: E501
        :type: datetime
        """

        self._modified_date = modified_date

    @property
    def product(self):
        """Gets the product of this ProductModel.  # noqa: E501


        :return: The product of this ProductModel.  # noqa: E501
        :rtype: list[Product]
        """
        return self._product

    @product.setter
    def product(self, product):
        """Sets the product of this ProductModel.


        :param product: The product of this ProductModel.  # noqa: E501
        :type: list[Product]
        """

        self._product = product

    @property
    def product_model_product_description(self):
        """Gets the product_model_product_description of this ProductModel.  # noqa: E501


        :return: The product_model_product_description of this ProductModel.  # noqa: E501
        :rtype: list[ProductModelProductDescription]
        """
        return self._product_model_product_description

    @product_model_product_description.setter
    def product_model_product_description(self, product_model_product_description):
        """Sets the product_model_product_description of this ProductModel.


        :param product_model_product_description: The product_model_product_description of this ProductModel.  # noqa: E501
        :type: list[ProductModelProductDescription]
        """

        self._product_model_product_description = product_model_product_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
