export * from './addresses.service';
import { AddressesService } from './addresses.service';
export * from './customerAddresses.service';
import { CustomerAddressesService } from './customerAddresses.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './errorLogs.service';
import { ErrorLogsService } from './errorLogs.service';
export * from './productCategories.service';
import { ProductCategoriesService } from './productCategories.service';
export * from './productDescriptions.service';
import { ProductDescriptionsService } from './productDescriptions.service';
export * from './productModelProductDescriptions.service';
import { ProductModelProductDescriptionsService } from './productModelProductDescriptions.service';
export * from './productModels.service';
import { ProductModelsService } from './productModels.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './salesOrderDetails.service';
import { SalesOrderDetailsService } from './salesOrderDetails.service';
export * from './salesOrderHeaders.service';
import { SalesOrderHeadersService } from './salesOrderHeaders.service';
export * from './values.service';
import { ValuesService } from './values.service';
export const APIS = [AddressesService, CustomerAddressesService, CustomersService, ErrorLogsService, ProductCategoriesService, ProductDescriptionsService, ProductModelProductDescriptionsService, ProductModelsService, ProductsService, SalesOrderDetailsService, SalesOrderHeadersService, ValuesService];
