/**
 * AdventureWorksAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerAddress } from './customerAddress';
import { SalesOrderHeader } from './salesOrderHeader';


export interface Address { 
    addressId?: number;
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    stateProvince?: string;
    countryRegion?: string;
    postalCode?: string;
    rowguid?: string;
    modifiedDate?: Date;
    customerAddress?: Array<CustomerAddress>;
    salesOrderHeaderBillToAddress?: Array<SalesOrderHeader>;
    salesOrderHeaderShipToAddress?: Array<SalesOrderHeader>;
}
