/**
 * AdventureWorksAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductModelProductDescription } from './productModelProductDescription';


export interface ProductDescription { 
    productDescriptionId?: number;
    description?: string;
    rowguid?: string;
    modifiedDate?: Date;
    productModelProductDescription?: Array<ProductModelProductDescription>;
}
