/**
 * AdventureWorksAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductDescription } from './productDescription';
import { ProductModel } from './productModel';


export interface ProductModelProductDescription { 
    productModelId?: number;
    productDescriptionId?: number;
    culture?: string;
    rowguid?: string;
    modifiedDate?: Date;
    productDescription?: ProductDescription;
    productModel?: ProductModel;
}
