/**
 * AdventureWorksAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductCategory { 
    productCategoryId?: number;
    parentProductCategoryId?: number;
    name?: string;
    rowguid?: string;
    modifiedDate?: Date;
    parentProductCategory?: ProductCategory;
    inverseParentProductCategory?: Array<ProductCategory>;
    product?: Array<Product>;
}
