/**
 * AdventureWorksAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';
import { ProductModelProductDescription } from './productModelProductDescription';


export interface ProductModel { 
    productModelId?: number;
    name?: string;
    catalogDescription?: string;
    rowguid?: string;
    modifiedDate?: Date;
    product?: Array<Product>;
    productModelProductDescription?: Array<ProductModelProductDescription>;
}
