/**
 * AdventureWorksAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductCategory } from './productCategory';
import { ProductModel } from './productModel';
import { SalesOrderDetail } from './salesOrderDetail';


export interface Product { 
    productId?: number;
    name?: string;
    productNumber?: string;
    color?: string;
    standardCost?: number;
    listPrice?: number;
    size?: string;
    weight?: number;
    productCategoryId?: number;
    productModelId?: number;
    sellStartDate?: Date;
    sellEndDate?: Date;
    discontinuedDate?: Date;
    thumbNailPhoto?: string;
    thumbnailPhotoFileName?: string;
    rowguid?: string;
    modifiedDate?: Date;
    productCategory?: ProductCategory;
    productModel?: ProductModel;
    salesOrderDetail?: Array<SalesOrderDetail>;
}
