# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product_categories_api import ProductCategoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductCategoriesApi(unittest.TestCase):
    """ProductCategoriesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.product_categories_api.ProductCategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_product_category(self):
        """Test case for delete_product_category

        """
        pass

    def test_get_product_category(self):
        """Test case for get_product_category

        """
        pass

    def test_get_product_category_0(self):
        """Test case for get_product_category_0

        """
        pass

    def test_post_product_category(self):
        """Test case for post_product_category

        """
        pass

    def test_put_product_category(self):
        """Test case for put_product_category

        """
        pass


if __name__ == '__main__':
    unittest.main()
