# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.error_logs_api import ErrorLogsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorLogsApi(unittest.TestCase):
    """ErrorLogsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.error_logs_api.ErrorLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_error_log(self):
        """Test case for delete_error_log

        """
        pass

    def test_get_error_log(self):
        """Test case for get_error_log

        """
        pass

    def test_get_error_log_0(self):
        """Test case for get_error_log_0

        """
        pass

    def test_post_error_log(self):
        """Test case for post_error_log

        """
        pass

    def test_put_error_log(self):
        """Test case for put_error_log

        """
        pass


if __name__ == '__main__':
    unittest.main()
