# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.addresses_api import AddressesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAddressesApi(unittest.TestCase):
    """AddressesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.addresses_api.AddressesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_address(self):
        """Test case for delete_address

        """
        pass

    def test_get_address(self):
        """Test case for get_address

        """
        pass

    def test_get_address_0(self):
        """Test case for get_address_0

        """
        pass

    def test_post_address(self):
        """Test case for post_address

        """
        pass

    def test_put_address(self):
        """Test case for put_address

        """
        pass


if __name__ == '__main__':
    unittest.main()
