# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.products_api import ProductsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_product(self):
        """Test case for delete_product

        """
        pass

    def test_get_product(self):
        """Test case for get_product

        """
        pass

    def test_get_product_0(self):
        """Test case for get_product_0

        """
        pass

    def test_post_product(self):
        """Test case for post_product

        """
        pass

    def test_put_product(self):
        """Test case for put_product

        """
        pass


if __name__ == '__main__':
    unittest.main()
