# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_log import ErrorLog  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorLog(unittest.TestCase):
    """ErrorLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorLog(self):
        """Test ErrorLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_log.ErrorLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
