# coding: utf-8

"""
    AdventureWorksAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customers_api import CustomersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.customers_api.CustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_customer(self):
        """Test case for delete_customer

        """
        pass

    def test_get_customer(self):
        """Test case for get_customer

        """
        pass

    def test_get_customer_0(self):
        """Test case for get_customer_0

        """
        pass

    def test_post_customer(self):
        """Test case for post_customer

        """
        pass

    def test_put_customer(self):
        """Test case for put_customer

        """
        pass


if __name__ == '__main__':
    unittest.main()
